# Redirect ingress destined for /s/cerebral-docs* to the new developers.workiva.com site
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "template.fullname" . }}
  labels:
    app: {{ template "template.name" . }}
    chart: {{ template "template.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($uri ~ ^/s/cerebral-docs(.*)$) {
        return 301 https://developers.workiva.com/workiva-wdata/reference;
      }
spec:
  tls:
    - hosts:
      - h.{{ required "ingress.clusterDomain is required" .Values.ingress.clusterDomain }}
      secretName: "default-ingress-cert"
  rules:
    - host: h.{{ .Values.ingress.clusterDomain }}
      http:
        paths:
          - backend:
              serviceName: {{ template "template.fullname" $ }}
              servicePort: 8000
            path: /s/cerebral-docs/(.*)
---
# Redirect ingress destined for /s/wdata-docs* to the new developers.workiva.com site
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "template.fullname" . }}
  labels:
    app: {{ template "template.name" . }}
    chart: {{ template "template.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($uri ~ ^/s/wdata-docs/prep(.*)$) {
        return 301 https://developers.workiva.com/workiva-wdata/reference;
      }
spec:
  tls:
    - hosts:
      - h.{{ required "ingress.clusterDomain is required" .Values.ingress.clusterDomain }}
      secretName: "default-ingress-cert"
  rules:
    - host: h.{{ .Values.ingress.clusterDomain }}
      http:
        paths:
          - backend:
              serviceName: {{ template "template.fullname" $ }}
              servicePort: 8000
            path: /s/wdata-docs/prep/(.*)
