---
# Default values for template.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Number of pods replicas to run.
replicas: 0

# Ingress configuration
# See: https://kubernetes.io/docs/concepts/services-networking/ingress/
# NOTE: Ingress for this repo now just redirects /s/cerebral-docs/ and
# /s/wdata-docs/prop/ to the new developers.workiva.net site.
# These rules are hardcoded in the ingress.yaml file, and the only input
# from here is the clusterDomain.
ingress:
  # Base domain for the cluster (ex. wk-dev.wdesk.org, app.wdesk.org).
  clusterDomain: ''

labels:
  servicecatalog.service: cerberus-docs
  automation.org-group: wdata
  servicecatalog.owner: data-prep
